### ISSUE TITLE
Expects static version of libadalang

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang-tools#2]
Makefile says
```
BUILD_MODE = dev
LIBRARY_TYPE = static
PROCESSORS = 0
```
which I think would be improved by
```
BUILD_MODE ?= dev
LIBRARY_TYPE ?= static
PROCESSORS ?= 0
```
which would allow us to set, for example, `LIBRARY_TYPE` via an environment variable.

I tripped over this because of https://github.com/AdaCore/libadalang/issues/174 (the static library isn’t built).

**Comment by pmderodat** [comment]
Hello Simon,

Good suggestion, this is now implemented. Thank you!
